import os

GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GITHUB_REPO = os.environ.get("GITHUB_REPO", "sararazadz-prog/my")
GITHUB_BRANCH = os.environ.get("GITHUB_BRANCH", "main")

PERSISTENT_DIR = os.environ.get("PERSISTENT_DIR", "/data")
CONSTITUTION_FILE = f"{PERSISTENT_DIR}/constitution.txt"
DB_PATH = f"{PERSISTENT_DIR}/constitution.db"
BOOKS_DIR = f"{PERSISTENT_DIR}/books"
CURRENT_BOOK_FILE = f"{PERSISTENT_DIR}/current_book.txt"
PENDING_QUESTIONS_FILE = f"{PERSISTENT_DIR}/pending_questions.json"
AGENT_ART_DIR = f"{PERSISTENT_DIR}/agent_art"
BASELINE_FILE = f"{PERSISTENT_DIR}/baseline.json"

QURAN_URL = "https://cdn.jsdelivr.net/npm/quran-json@3.1.2/dist/quran.json"

MAX_BOOK_SIZE = 10 * 1024 * 1024
MAX_CODE_EXECUTION_TIME = 5
MAX_EVOLUTIONS_PER_DAY = 3
MAX_SANDBOX_MEMORY_MB = 256
MAX_REQUESTS_PER_MINUTE = 10

LEARNING_INTERVAL = 1800
CURIOSITY_INTERVAL = 3600
EVOLUTION_CHECK_INTERVAL = 3600
BACKUP_INTERVAL_ITERATIONS = 50
AGENT_DRAW_INTERVAL = 60000

CONSTITUTION_WEIGHT = 1.0
BOOK_WEIGHT = 0.3
